version: '4'
services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fileingest
      POSTGRES_PASSWORD: fileingest
      POSTGRES_DB: fileingestsystem
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: